### ISSUE TITLE
登陆扫码界面打不开了

### ISSUE THREAD

**Issue by FunnyFly-ZW** [v2018z/xueXiQiangguo#102]
如题

**Comment by FunnyFly-ZW** [comment]
> 已修复上传到网盘了，链接: https://pan.baidu.com/s/1LDNupQzyaNuQRYo99C3qWA?pwd=ux3i 提取码: ux3i

1.1.2试过了，缺少ffmpeg.dll，还是不行

**Comment by v2018z** [comment]
这两天忙，争取明天解决。

**Comment by v2018z** [comment]
仓库新上传了，试试看

**Comment by FunnyFly-ZW** [comment]
> 仓库新上传了，试试看

没问题了，感谢大佬
