### ISSUE TITLE
大佬，最新版显示：应用程序无法正常启动0xc000007b，要么显示缺少ffmpeg.dll

### ISSUE THREAD

**Issue by silict** [v2018z/xueXiQiangguo#103]
恳请解决。

**Comment by v2018z** [comment]
试试这个 https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

**Comment by silict** [comment]
> 试试这个 https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

非常感谢！！！
