### ISSUE TITLE
大佬 1.1.2版本提示ffmpeg.dll文件丢失 自行在网上下载dll安装后提示0xc000007b错误 希望大佬看到后能修复下 在此谢谢了

### ISSUE THREAD

**Issue by Marvel0914** [v2018z/xueXiQiangguo#104]

**Comment by v2018z** [comment]
你是32位系统还是64位的？

**Comment by Marvel0914** [comment]
Win10 64位

**Comment by rigolang** [comment]
都是一样的 缺少ffmpeg.dll  Win10 64位

**Comment by tszpl** [comment]
你们那下的1.1.2 我怎么看不到？

**Comment by rigolang** [comment]
> 你们那下的1.1.2 我怎么看不到？

撤包了，应该是有问题回炉了

**Comment by silict** [comment]
windows 11，同样的问题。

**Comment by xuehuasu** [comment]
大佬加油，爱你.jpg

**Comment by v2018z** [comment]
试试这个：https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

**Comment by Marvel0914** [comment]
> 试试这个：https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

感谢大佬

**Comment by tszpl** [comment]
万分感谢🙏  好人一生平安 好人一生幸福！
