### ISSUE TITLE
Win10 三天前的版本提示ffmpeg.dll文件丢失，下载dll后又提示0xc000007b错误，希望能有后续版本

### ISSUE THREAD

**Issue by dmg127113** [v2018z/xueXiQiangguo#106]
Win10 三天前的版本提示ffmpeg.dll文件丢失，下载dll后又提示0xc000007b错误，希望能有后续版本

**Comment by v2018z** [comment]
试试这个：https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

**Comment by xuehuasu** [comment]
> 试试这个：https://github.com/v2018z/xueXiQiangguo/tree/main/build/Windows

有用，大佬太强了🤩
