### ISSUE TITLE
谢谢分享，方便提供源码参考吗 

### ISSUE THREAD

**Issue by JackyTianer** [v2018z/xueXiQiangguo#4]

**Comment by v2018z** [comment]
[戳这里](https://github.com/v2018z/studyxixi)

**Comment by v2018z** [comment]
[可以戳这里](https://github.com/v2018z/studyxixi)

**Comment by JackyTianer** [comment]
> [可以戳这里](https://github.com/v2018z/studyxixi)
谢谢~
