### ISSUE TITLE
从昨天开始，打开之后确实没有扫码登录的页面，但是可以在开始菜单栏里面，用鼠标选中有二维码的那个窗口可以进行扫码。

### ISSUE THREAD

**Issue by zx122248006** [v2018z/xueXiQiangguo#63]
![1639106577(1)](https://user-images.githubusercontent.com/16813650/145511944-52b60a1c-b83d-48a4-898b-a0118e3d8d4a.png)

**Comment by v2018z** [comment]
问题已解决，请下载 1.0.8 版本

**Comment by zx122248006** [comment]
感谢～
