### ISSUE TITLE
[提议]有没有可能可以加个推送

### ISSUE THREAD

**Issue by BlackTitle** [v2018z/xueXiQiangguo#71]
比如加个微信推送或者QQbot推送，因为加了个自动每天刷，所以在想这个事
谢谢嫂子，让我们用上这么好用的软件💪🏼

**Comment by iSun0613** [comment]
还要调用接口 太麻烦了 电脑不关机软件一直打开就可以了

**Comment by v2018z** [comment]
暂时没有这个想法，似乎有这个需求的同学不多哦。有重写计划后会考虑。
有推荐哪家推送API比较好用吗？

**Comment by BlackTitle** [comment]
> 暂时没有这个想法，似乎有这个需求的同学不多哦。有重写计划后会考虑。
> 有推荐哪家推送API比较好用吗？

微信的的话只知道wxpusher和sever酱。QQbot不清楚

**Comment by v2018z** [comment]
> > 暂时没有这个想法，似乎有这个需求的同学不多哦。有重写计划后会考虑。
> > 有推荐哪家推送API比较好用吗？
> 
> 微信的的话只知道wxpusher和sever酱。QQbot不清楚

好的，谢谢你。
