### ISSUE TITLE
[bug?]专项答题失效

### ISSUE THREAD

**Issue by BlackTitle** [v2018z/xueXiQiangguo#85]
系统版本:Windwos 11 22H2 25115.1000
软件版本:Windows免安装版 V2.1 1.0.9-portable_2
软件报错:无报错，但长时间提示正在执行且有提示今日积分已满。
log:无
网络环境:可以正常上网且开关梯子均有测试

**Comment by BlackTitle** [comment]
参考已关闭的issues补充，重启任务和答题菜单中均已点击，无加分情况

**Comment by v2018z** [comment]
打开App看看最近的专项答题是不是都答完了，远古时期的专项答题不会做的。

**Comment by BlackTitle** [comment]
> 打开App看看最近的专项答题是不是都答完了，远古时期的专项答题不会做的。

是这样  只剩下远古的了
