### ISSUE TITLE
今天无法使用了～

### ISSUE THREAD

**Issue by xujie27296** [v2018z/xueXiQiangguo#88]

**Comment by Aighook** [comment]
一样的，都卡在扫登录后加载中。。。

**Comment by 123ynnr** [comment]
可以用了

**Comment by rigolang** [comment]
> 

骗纸

**Comment by xujie27296** [comment]
我是Mac，现在还没能用

**Comment by v2018z** [comment]
我这边测试没问题，大家可以用了吗？

**Comment by FunnyFly-ZW** [comment]
从未出现过问题

**Comment by laohanhanhan2020** [comment]
老哥，我也是遇到问题了，就是分数一栏一直加载，任务也不会自动完成，几个版本都试了，目前没有办法，老哥能不能解决下，替我向嫂子问好

**Comment by v2018z** [comment]
> 老哥，我也是遇到问题了，就是分数一栏一直加载，任务也不会自动完成，几个版本都试了，目前没有办法，老哥能不能解决下，替我向嫂子问好

目前强国自己的app或网站你能正常使用吗？

**Comment by zmyhl** [comment]
我总结了下 

> > 老哥，我也是遇到问题了，就是分数一栏一直加载，任务也不会自动完成，几个版本都试了，目前没有办法，老哥能不能解决下，替我向嫂子问好
> 
> 目前强国自己的app或网站你能正常使用吗？

老铁，我总结了一下，部分人的账号不能用，有些人的账号又可以用，我观察了下，不能用的账号推测是获取不到积分，但是能正常每日答题，不会再自动学习文章和视频。

**Comment by laohanhanhan2020** [comment]
> > > 老哥，我也是遇到问题了，就是分一栏一直播，任务也不会自动完成，几个版本都试了，目前没法办，老哥不能解压下来，代替子吧
> > 
> > 
> > 当前强国自己的app或者网站你能正常使用吗？
> 
> 老铁，我总算了下，部分人的账号不能用，有些人的账号又可以用，我观察了下，不能用的账号推测是得不到积分，但能正常每天回答题目，只是不会再自主学习文章和视频。感觉那些账号应该被限制制定了获取积分方式？

老哥，你说的情况我不太了解，我网页版的脚本还是可以正常使用，但每次答完题都有要滑动验证的情况，不知道是不是这个原因

**Comment by huangjiayun2023** [comment]
扫码登陆后一直加载中，分数不加，通过网页插件脚本学习，能够获取分数，就是每日答题做完会有滑块

**Comment by huangjiayun2023** [comment]
刚开了个小号，能够登录软件正常跑分，估计我的老号已经被限制，不知道是否可以不要做题目，只挂时长，来解决这个问题

**Comment by huangjiayun2023** [comment]
刚开了个小号，能够登录软件正常跑分，估计我的老号已经被限制，不知道是否可以不要做题目，只挂时长，来解决这个问题。

**Comment by huangjiayun2023** [comment]
刚开了个小号，能够登录软件正常跑分，估计我的老号已经被限制，不知道是否可以不要做题目，只挂时长，来解决这个问题。

**Comment by XiaozxJx** [comment]
> 扫码登陆后一直加载中，分数不加，通过网页插件脚本学习，能够获取分数，就是每日答题做完会有滑块

老哥，网页插件介绍一下？

**Comment by XiaozxJx** [comment]
> 刚开了个小号，能够登录软件正常跑分，估计我的老号已经被限制，不知道是否可以不要做题目，只挂时长，来解决这个问题

我有两个号，一个正常，一个一直卡在加载中

**Comment by FunnyFly-ZW** [comment]
> 

App和网页还能正常获得积分，因此排除账号限制，估计是接口又出问题了，别慌。呼唤大佬更新一下

**Comment by FunnyFly-ZW** [comment]
> > > 老哥，我也是遇到问题了，就是分数一栏一直加载，任务也不会自动完成，几个版本都试了，目前没有办法，老哥能不能解决下，替我向嫂子问好
> > 
> > 
> > 目前强国自己的app或网站你能正常使用吗？
> 
> 老铁，我总结了一下，部分人的账号不能用，有些人的账号又可以用，我观察了下，不能用的账号推测是获取不到积分，但是能正常每日答题，只是不会再自动学习文章和视频。感觉那些账号应该被限制了获取积分方式？

App和网页还能正常获得积分，因此排除账号限制，估计是接口又出问题了，别慌。呼唤大佬更新一下

**Comment by v2018z** [comment]
修改了一波，下载1.1.0 版本试用。。至于某些可能被封的账号，我也无能为力😂

**Comment by 1121141166** [comment]
我这边提示 由于找不到ffmpeg.dll.无法继续执行代码

**Comment by v2018z** [comment]
> 我这边提示 由于找不到ffmpeg.dll.无法继续执行代码

重新下载再试试看。

**Comment by v2018z** [comment]
windows可能会碰到电脑提示阻止的问题，选择仍要运行就好。。暂时不知道什么原因引起的

**Comment by michaelleeneo** [comment]
1.1.0版本无法下载

**Comment by rigolang** [comment]
> 1.1.0版本无法下载

挂代理下载

**Comment by laohanhanhan2020** [comment]
> windows可能会碰到电脑提示停止的问题，选择仍然要运行就好。。暂时不知道什么原因引起的

可以了，谢谢老哥
