### ISSUE TITLE
大佬每日答题获取失败

### ISSUE THREAD

**Issue by yangan0724** [v2018z/xueXiQiangguo#90]
其他功能都正常，但是每日答题获取失败。

**Comment by XiaozxJx** [comment]
同样的问题，两个号，一个号正常，一个号不每日答题。
和前两天卡加载中一个的情况原因，不卡加载中的号能每日答题，卡加载中的号不做每日答题。

**Comment by v2018z** [comment]
> 同样的问题，两个号，一个号正常，一个号不每日答题。 和前两天卡加载中一个的情况原因，不卡加载中的号能每日答题，卡加载中的号不做每日答题。

最近似乎有不少人有类似问题，方便把你不正常的账号信息用邮件发我调试下么。我这边没办法复现～

**Comment by XiaozxJx** [comment]
> 

已发你邮箱了。

**Comment by v2018z** [comment]
> > 
> 
> 已发你邮箱了。

OK 问题已知晓。请自己手动去网站拖一下验证条，下次再用App似乎就好了
