### ISSUE TITLE
windows 1.1.1 版本无法自动答题

### ISSUE THREAD

**Issue by warne-wyp** [v2018z/xueXiQiangguo#94]
大佬，自动答题失效了，求修复

**Comment by sy007007** [comment]
每日答题无法自动答题，请修复~~~

**Comment by sy007007** [comment]
学习强国V2.1 1.1.2.exe 无法在任务栏固定快捷方式，当固定快捷方式后，关闭窗口，点击任务栏快捷方式显示：该快捷方式所指向的项目”学习强国 V2.1. exe"已经更改或移动，因此该快捷方式无法正常工作。
是否删除该快捷方式？
请修复~~~

                       
原始邮件
                       
                     

发件人："jax"< ***@***.*** &gt;;

发件时间：2024/3/6 21:42

收件人："v2018z/xueXiQiangguo"< ***@***.*** &gt;;

抄送人："sy007007"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [v2018z/xueXiQiangguo] windows 1.1.1 版本无法自动答题 (Issue #94)




 
Closed #94 as completed.
